In [1]:
import numpy as np

In [2]:
data = [1,2,3,4]
first_array = np.array(data)
first_array

array([1, 2, 3, 4])

In [4]:
np.ones(12)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.zeros(3)

array([0., 0., 0.])

In [6]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [7]:
np.arange(3,12,4)

array([ 3,  7, 11])

In [8]:
oned = np.arange(21)
oned

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [9]:
oned.shape

(21,)

In [10]:
oned.ndim

1

In [11]:
oned.size

21

In [13]:
list_o_lists = [
    [1,2,3],
    [4,5,6],
    [7,8,9],
]
twod = np.array(list_o_lists)
twod

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
twod.ndim

2

In [15]:
twod.size

9

In [17]:
twod.shape

(3, 3)

In [18]:
oned = np.arange(12)
oned

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [19]:
twod = oned.reshape(3,4)
twod

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [20]:
twod.shape

(3, 4)

In [21]:
twod.ndim

2

In [23]:
twod.reshape(2,2,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [24]:
darray = np.arange(100)
darray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [25]:
darray.dtype

dtype('int32')

In [26]:
darray.size

100

In [27]:
darray.nbytes

400

In [28]:
darray2 = np.arange(100, dtype=np.int8)
darray2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
      dtype=int8)

In [30]:
darray2.nbytes

100

In [31]:
darray[12] = "a"

ValueError: invalid literal for int() with base 10: 'a'

In [32]:
darray[12] = 0.4

In [33]:
darray[12]

0

### Broadcast

In [34]:
A1 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
])

In [35]:
A1.shape

(3, 3)

In [36]:
A2 = np.array([
    [1,1,1],
    [1,1,1],
    [1,1,1],
])

In [37]:
A1 + A2

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [38]:
A1 + 3 

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [39]:
A3 = np.array([1,1,1])

In [40]:
A3.shape

(3,)

In [41]:
A1 + A3

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [42]:
A4 = np.arange(10).reshape(2,1,5)
A4

array([[[0, 1, 2, 3, 4]],

       [[5, 6, 7, 8, 9]]])

In [43]:
A5 = np.arange(14).reshape(2,7,1)
A5

array([[[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6]],

       [[ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13]]])

In [44]:
A6 = A4 + A5
A6

array([[[ 0,  1,  2,  3,  4],
        [ 1,  2,  3,  4,  5],
        [ 2,  3,  4,  5,  6],
        [ 3,  4,  5,  6,  7],
        [ 4,  5,  6,  7,  8],
        [ 5,  6,  7,  8,  9],
        [ 6,  7,  8,  9, 10]],

       [[12, 13, 14, 15, 16],
        [13, 14, 15, 16, 17],
        [14, 15, 16, 17, 18],
        [15, 16, 17, 18, 19],
        [16, 17, 18, 19, 20],
        [17, 18, 19, 20, 21],
        [18, 19, 20, 21, 22]]])

In [45]:
#  take max size for each dim
A6.shape

(2, 7, 5)

In [46]:
M1 = np.arange(9).reshape(3,3)
M1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [47]:
M2 = np.arange(2,11).reshape(3,3)
M2

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [49]:
M1.transpose()

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [50]:
M1.diagonal()

array([0, 4, 8])

In [51]:
M1 @ M2

array([[ 21,  24,  27],
       [ 66,  78,  90],
       [111, 132, 153]])